<Project Sdk="Godot.NET.Sdk/4.6.3">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <GodotGenerateBindings>false</GodotGenerateBindings>
        <GodotDisableAssemblyReload>false</GodotDisableAssemblyReload>
        <UseSharedCompilation>true</UseSharedCompilation>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Fody" Version="6.8.0" PrivateAssets="all" />
        <PackageReference Include="GTweensGodot" Version="6.0.0" />
        <WeaverFiles Include="$(MSBuildThisFileDirectory)Generators\bin\Debug\netstandard2.0\NodeWire.Fody.dll" WeaverClassNames="NodeWireWeaver;MustAssignWeaver" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Generators/**" />
        <Compile Remove="tasks/example_task/**" />
    </ItemGroup>
</Project>